export const SPORT = [
    { code: "TC", name: "หมากฮอสไทย" },
    { code: "SB", name: "ซอฟท์บอล" },
    { code: "TN", name: "เทนนิส" },
    { code: "HK", name: "ฮอกกี้ในร่ม 4 คน" },
    { code: "BD", name: "แบดมินตัน" },
    { code: "GN", name: "ยิงปืน" },
    { code: "FS", name: "ฟุตซอล" },
    { code: "FB", name: "ฟุตบอล" },
    { code: "BK", name: "บาสเกตบอล" },
    { code: "VB", name: "วอลเลย์บอล" },
    { code: "VA", name: "Valorant" },
    { code: "RO", name: "RoV" },
    { code: "GO", name: "พัตต์กอล์ฟ" },
    { code: "AM", name: "เอแมท" },
    { code: "GO", name: "หมากล้อม" },
    { code: "RW", name: "กรรเชียงบก" },
    { code: "BR", name: "บริดจ์" },
    { code: "TCH", name: "หมากรุกไทย" },
    { code: "BS", name: "เบสบอล" },
    { code: "AH", name: "กรีฑา" },
    { code: "HB", name: "แฮนด์บอลในร่ม" },
    { code: "RB", name: "รักบี้ฟุตบอล" },
    { code: "BX", name: "มวยสากลสมัครเล่น" },
    { code: "PD", name: "กระดานยืนพาย" },
    { code: "CW", name: "ครอสเวิร์ด" },
    { code: "CF", name: "Crossfit(เพาะกายและฟิตเนส)" },
    { code: "DC", name: "ลีลาศ" },
    { code: "ICH", name: "หมากรุุกสากล" },
    { code: "SW", name: "กระบี่บุคคล" },
    { code: "THSW", name: "ดาบสองมือบุคคล" },
]